### ISSUE TITLE
Recommendations for converting a font from adafruit graphics?

### ISSUE THREAD

**Issue by lambtor** [cbm80amiga/RREFont#1]
I am looking to use this library in an Arduino project, but I need to use a specific font.  What is the easiest way to convert a ttf or adafruit graphics .h file into the RREFont expected format?

**Comment by lambtor** [comment]
Ignore this question - found the font conversion project you created.

**Comment by cbm80amiga** [comment]
Try to use https://github.com/cbm80amiga/rrefontgen, but there is no direct way of converting ttf
