### ISSUE TITLE
Missing tagged release

### ISSUE THREAD

**Issue by alranel** [cbm80amiga/RREFont#3]
Hi! This is a great library. :)
I'm trying to add it to the Arduino library index to make it available in the Arduino IDE and CLI, and to let other developers create libraries that depend on this one. As you see the submission gives an error because this repository does not have any tagged release:

https://github.com/arduino/library-registry/pull/547

You should simply tag a release named `1.0.1` (which is the current `version` written in library.properties).

Thank you!

**Comment by per1234** [comment]
Hi @cbm80amiga. I'm just checking in to see if you have had the time to take a look at this request. I also think it would be wonderful to have this library available for installation and updates via the Arduino Library Manager.

If you have any questions or concerns, I'm happy to provide more information.

**Comment by cbm80amiga** [comment]
Hi! I created release and new tag - is it enough for ALM?

**Comment by per1234** [comment]
That is perfect. The library has now been accepted into Arduino Library Manager:
https://github.com/arduino/library-registry/pull/547#issuecomment-975356614

It will be available to the users for installation via the Arduino IDE and Arduino CLI within the next day (it takes a little time to work its way through the cache).

Thanks @cbm80amiga!
